regressionTest {
    FILE_PATH =  "src/app.js"
    LINE_NUM =  "7"
    SHA =  "864beed7f8f122e8801f573e750b0aa9b77a5354c91d7e21f7a854151416a8fe"
    TRIGGER_TIME = "4"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "node /src/app.js &"
    URL_FOR_TRIGGER = "http://localhost:3000"
}
