def label = "true".equals(env.SAME_LABEL) ? env.PROFILE : "worker-${UUID.randomUUID().toString()}"
def testDir = 'java-gradle'
def workingDir = "deployment_example/${testDir}"
def dockerTag = "us.gcr.io/rookout/deployment-example-${testDir}:latest"
podCreator.init(label: label) {
    node(label) {
        stage('Build And Push docker Images') {
            withEnv(["DOCKER_HOST=tcp://dind:2375"
                ]) {
                    container('rookout-helm') {
                        githubWrapper.clone(repo: 'deployment-examples', branchToClone: 'adding-jenkins-test') {
                    sh("docker build ${testDir} -t ${dockerTag} && gcloud docker -- push ${env.docker_master_tag}")
                    }
                    }
                }
        }
    }
}