regressionTest {
    FILE_PATH =  "app.js"
    LINE_NUM =  "32"
    SHA =  "7ef9f8d2a2969121af0da1769059e8bdd4aac97a70a21724aef5eedada13a0c8"
    URL_FOR_TRIGGER = "http://node-aws-ebs-reg-test.us-east-2.elasticbeanstalk.com/"
    LANG = "Node"
    BACKGROUND_IMAGE_CMD = "bash /runTest.sh &"
}