regressionTest {
    FILE_PATH =  "app.js"
    LINE_NUM =  "32"
    SHA =  "f818b9cd82d383b21bc8bc14f0d59caa9ceae3802132a480d6e565939cda673b"
    URL_FOR_TRIGGER = "http://node-aws-ebs-reg-test.us-east-2.elasticbeanstalk.com/"
    LANG = "Node"
    BACKGROUND_IMAGE_CMD = "bash /runTest.sh &"
    STATIC_LABEL = "node-aws-ebs-reg-test"
}