regressionTest {
    FILE_PATH =  "src/app.ts"
    LINE_NUM =  "27"
    SHA =  "fa167d9a3515a51d4be15b4fbe067ed9f9de6d4e15902bc820e0b02b1e236d18"
    TRIGGER_TIME = "4"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "node /dist/app.js &"
}
