apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rookout-agent-deployment
  labels:
    product: rookout
    app: agent
    type: deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        product: rookout
        app: agent
    spec:
      containers:
      - name: agent
        image: rookout/agent
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.03"
            memory: "32Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
          - name: ROOKOUT_TOKEN
            valueFrom:
              secretKeyRef:
                name: rookout
                key: token
        ports:
          - containerPort: 7486
        livenessProbe:
          tcpSocket:
            port: 7486
          initialDelaySeconds: 15
          periodSeconds: 20