kind: Service
apiVersion: v1
metadata:
  name: rookout-controller-service
  labels:
    product: rookout
    app: controller
    type: service
spec:
  selector:
    product: rookout
    app: controller
    type: deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7486