apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rookout-demo-app-deployment
  labels:
    name: rookout-demo-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rookout-demo-app-deployment
    spec:
      containers:
      - name: rookout-demo-app
        image: rookout/tutorial-python
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: ROOKOUT_TOKEN
            valueFrom:
              secretKeyRef:
                name: rookout
                key: token
