apiVersion: v1
kind: Service
metadata:
  name: rookout-demo-app-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    name: rookout-demo-app-deployment
  type: LoadBalancer