regressionTest {
    FILE_PATH =  "index.js"
    LINE_NUM =  "13"
    SHA =  "65c176e5a4e694fded082bf476ef7dd14daa20b98d999b04c2a263380f474c02"
    URL_FOR_TRIGGER = "node-serverless-regression-test-dev"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "bash /app/runTest.sh &"
}