service: aws-nodejs

app: node-serverless-app
tenant: your-tenant

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.defaultRegion}
custom:
    defaultRegion: us-east-2

functions:
  example:
    handler: index.handler
    events:
      - http: ANY /
