regressionTest {
    FILE_PATH =  "src/main/java/com/rookout/HelloWorld.java"
    LINE_NUM =  "24"
    SHA =  "0e72c93aba4a7ae483cba99d886360629a57ceca73a26983327aee27e6696680"
    URL_FOR_TRIGGER = "http://localhost:7000/hello/ori"
    LANG = "Java"
    BACKGROUND_IMAGE_CMD = "ls ../java-gradle-java-api/gradlew &"
}
