regressionTest {
    FILE_PATH =  "flask_rookout.py"
    LINE_NUM =  "26"
    SHA =  "ff977376cd104bb6be77e3354a2699d28eb07ccf145178bc7d389072133907bc"
    URL_FOR_TRIGGER = "http://localhost:5000/render"
    LANG = "Python"
    BACKGROUND_IMAGE_CMD = "python /flask_rookout.py &"

}
