regressionTest {
    FILE_PATH =  "handler.py"
    LINE_NUM =  "21"
    SHA =  "4035cc4c07afe12680fd04b940022592919b46d663c2415b27887ba56f66d60d"
    URL_FOR_TRIGGER = "python-aws-serverless-reg-test-dev-hello"
    LANG = "Python"
    BACKGROUND_IMAGE_CMD = "bash /app/testEnvs.sh &"
}
