cd /app 
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
export ROOKOUT_TOKEN=$ROOKOUT_TOKEN
export ROOKOUT_DEBUG=1