regressionTest {
    withCredentials([
        usernamePassword(credentialsId: 'AWS_TEST_USER', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')
    ]){
        FILE_PATH =  "src/main/java/TestLambda/TestLambda.java"
        LINE_NUM =  "53"
        SHA =  "938ab95c0f454bce007bc1b6d128f0f7a6f113ae5d559c765886e170867aa5d1"
        URL_FOR_TRIGGER = "http://google.com"
        LANG = "Java"
        BACKGROUND_IMAGE_CMD = "docker run --rm -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} rookout_lambda_test &"
    }
}
