regressionTest {
    FILE_PATH =  "example.py"
    LINE_NUM =  "24,42"
    SHA =  "5be05e77248c57e27f95f1ce498d47844f97994f08d80e077597f2f6c43c1f51"
    TRIGGER_TIME = "30"
    LANG = "Python"
    BACKGROUND_IMAGE_CMD = "(sleep 30; spark-submit --conf spark.python.daemon.module=rook.pyspark_daemon /app/example.py) &"
}
