import org.rookout.files.Utilities
import org.rookout.testsUtil.TestUtilities

def label = "worker-${UUID.randomUUID().toString()}"

podCreator.initMain(label: label) {
    node(label) {
        print(pwd())
        container('rookout-helm') {
            stage ('Getting test') {

                def myRepo = checkout scm
                def scriptToUse = libraryResource 'generate_tests.groovy'
                print(pwd())
                def testsNamesRaw = Utilities.getAllDirThatMatchFile(this, '.', 'Jenkinsfile')
                def testsNames = testsNamesRaw.values().toList()
                println(testsNames)
            }
            stage ('Creating tests and building docker files') {
                for (int i = 0; i < testsNames.size(); i++) {
                    def jobName = "${testsNames[i]}"
                    def dockerTag = "us.gcr.io/rookout/reggresion-test-${jobName}:latest"
                    sh("cd ${jobName} && docker build . -t ${dockerTag} && gcloud docker -- push ${dockerTag}")
                    TestUtilities.createTest(this, scriptToUse, jobName, pwd() + "/${testsNames[i]}")
                }
            }
            stage ('Run the tests') {
                fullReggressionTest {
                    GIT_BRANCH = "$GIT_BRANCH"
                }
            }
        }
    }

}

