pipeline {
    agent none
    stages {
        stage('Build') {
            agent any
            steps {
            println(pwd)
            jobDsl(targets: '.jenkins/generate_tests.groovy',
                removedJobAction: 'DELETE',
                removedViewAction: 'DELETE',
                lookupStrategy: 'SEED_JOB',
                additionalParameters: [message: 'java-gradle', realpwd: pwd]
                )
            }
        }
    }
}
