regressionTest {
    FILE_PATH =  "app.py"
    LINE_NUM =  "7"
    SHA =  "4de4fa45b00152327dc2892d0bfb2eb6a2ed53ea22bda7dee319ecb97299e239"
    URL_FOR_TRIGGER = "python-aws-chalice-dev"
    LANG = "Python"
    BACKGROUND_IMAGE_CMD = "ls &"
}