build prod:
		sbt dist		
		unzip target/universal/play-java-starter-example-1.0-SNAPSHOT.zip 
run prod:
		chmod +x play-java-starter-example-1.0-SNAPSHOT/bin/play-java-starter-example
		play-java-starter-example-1.0-SNAPSHOT/bin/play-java-starter-example -Dplay.file=../conf/application.conf
