# use your node version
FROM lambci/lambda:build-nodejs12.x

# install serverless framework
RUN npm install -g serverless

# make room for our application in /app
RUN mkdir app
WORKDIR /app

# copy package dependencies
COPY package.json package-lock.json ./

# install app dependencies
RUN npm install

# copy our application contents
COPY . .

RUN sed -i '1s/.*/service: node-serverless-reg-test/' serverless.yml