regressionTest {
    FILE_PATH =  "index.js"
    LINE_NUM =  "8"
    SHA =  "f22045aa01ee2a854fa578b9ebb6fc1283247877ceddf24865bb523d662da8b7"
    URL_FOR_TRIGGER = "node-serverless-reg-test-dev-example"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "bash /app/runTest.sh &"
    STATIC_LABEL = "node-serverless-reg-test-dev-example"
}