regressionTest {
    FILE_PATH =  "src/app.ts"
    LINE_NUM =  "33"
    SHA =  "7559c53d67fe1aaa41d1e7162a92aca9868edd25c565e219b04b703693910c65"
    TRIGGER_TIME = "4"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "node /dist/app.js &"
}