regressionTest {
    FILE_PATH =  "electron_main.js"
    LINE_NUM =  "418"
    SHA =  "3d26b206a91768059d6be90545428a13c25fc9dc8fe1a8d054aeb45970ee27b4"
    TRIGGER_TIME = "7"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "node /electron_main.js &"
}