regressionTest {
    FILE_PATH =  "index.js"
    LINE_NUM =  "4"
    SHA =  "6354f3b20051c5dc72270653e1de88349252e40b4d2de6b450bedf11277ceb90"
    URL_FOR_TRIGGER = "node_aws_lambda_regression_test"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "bash /build/awsTest.sh &"
}
