regressionTest {
    FILE_PATH =  "index.js"
    LINE_NUM =  "4"
    SHA =  "101626e7ca39bef478ccc912ac89df34f3a48934cf534a760456f256d03505e4"
    URL_FOR_TRIGGER = "node_aws_lambda_regression_test"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "bash /awsTest.sh &"
}
