regressionTest {
    FILE_PATH =  "src/app.ts"
    LINE_NUM =  "19"
    SHA =  "2d5244ac891e124bf563a6fc4fe15b70247ed1aae5e55f7edaa96c1596515d26"
    TRIGGER_TIME = "4"
    LANG = "NodeJs"
    BACKGROUND_IMAGE_CMD = "node /dist/app.js &"
    URL_FOR_TRIGGER = "http://localhost:5000/hello/ben"
}
