version: '2'
services:
  wildfly-helloworld:
    container_name: wildfly-helloworld
    restart: always
    build: .
    environment:
      - ROOKOUT_AGENT_HOST=rookout-agent
    ports:
      - "80:8080"
    links:
      - rookout-agent
  rookout-agent:
    container_name: rookout-agent
    image: rookout/agent
    environment:
      - ROOKOUT_TOKEN=YOUR_TOKEN
    ports:
      - "7486:7486"