version: '3'
environment:
  ROOKOUT_TOKEN: YOUR_TOKEN_HERE

services:
  app:
    build: .
    container_name: rookout-demo-app
    ports:
      - 7000:7000
    command:  java  -javaagent:rook.jar -jar target/rookoutDemo-1.0.0.jar


