initdirs: mkdir output && mkdir target
compile: javac src/httpserver/* -d output
build: jar cvfm target/server.jar Manifest.txt -C output/ . src/*
getrook: wget "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.rookout&a=rook&v=LATEST"  -O rook.jar
