regressionTest {
    FILE_PATH =  "nameko_example.py"
    LINE_NUM =  "10"
    SHA =  "4296857248ac51dceeb1c59102c5d296e1e154d9592277c17f0e9ec7e7be0d10"
    URL_FOR_TRIGGER = "http://localhost:8000/get/42"
    LANG = "Python"
    BACKGROUND_IMAGE_CMD = "cd /nameko; nameko run nameko_example &"
    USE_WEBSOCKET_PROTOCOL = "true"
}
