apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rookout-agent-deployment
  labels:
    product: rookout
    app: agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        product: rookout
        app: agent
    spec:
      containers:
      - name: agent
        image: rookout/agent
        resources:
          limits:
            memory: "0.5Gi"
            cpu: "0.5"
        env:
          - name: ROOKOUT_TOKEN
            value: YOUR_TOKEN
        ports:
          - containerPort: 7486
        livenessProbe:
          tcpSocket:
            port: 7486
          initialDelaySeconds: 15
          periodSeconds: 20