regressionTest {
    FILE_PATH =  "fork_rookout.py"
    LINE_NUM =  "19,24"
    SHA =  "1a21d0c11ab8722f0303a06c15d9b15c71ba720559052fcfe85c9b4f32b5a1a7"
    URL_FOR_TRIGGER = "http://localhost:5000/hello"
    LANG = "Python"
    BACKGROUND_IMAGE_CMD = "python /fork_rookout.py &"

}
